### Useful code fragments

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import random

#### Normal Equation

In [ ]:
theta = inv(X.T @ X) @ X.T @ y

#### Standardize

In [ ]:
X = (X-np.mean(X, axis = 0))/np.std(X, axis = 0)

#### Augmenting X

In [ ]:
XX_norm = np.insert(X_norm, 0, 1, axis=1)

#### Reshaping

In [ ]:
x = x.reshape(-1,1) # convert from 1d array to 2d (matrix) 

y = y.reshape(m,1)

#### Train Test Split

In [ ]:
import random
random.seed(12)

percent_train = .6

# Partion data into training and test datasets
m, n = X.shape

y = y.reshape(m, 1)
idx = np.arange(0, m)
random.shuffle(idx)
m_train = int(m * percent_train)
train_idx = idx[0:m_train]
test_idx = idx[m_train:]
X_train = XX[train_idx,:]
X_test = XX[test_idx,:]

y_train = y[train_idx]
y_test = y[test_idx]

In [ ]:
X_train = np.insert(X_train, 0, 1, axis=1)
X_test = np.insert(X_test, 0, 1, axis=1)

#### Normalization

In [ ]:
def normalization(X):
    X_norm = None
    
    mean = np.mean(X, axis=0)
    std = np.std(X, axis=0)
    
    X_norm = (X - mean)/std
    
    return X_norm

#### List to Array

In [ ]:
# initializing list
lst = [1, 7, 0, 6, 2, 5, 6]
 
# converting list to array
arr = np.asarray(lst) # In place a copy is not made

arr = numpy.array(lst) # A copy is made



#### Theta Initial

In [4]:
#(n,1)
m,n = X.shape
theta_initial = np.ones((n, 1)) # (3,1) is the shape

#### Extracting Panda to NumPy

In [ ]:
feature_col_idx = new_df.columns.get_indexer(['island', 'culmen_length_mm', 'culmen_depth_mm','flipper_length_mm', 'body_mass_g'])
feature_col_idx


target_col_idx = new_df.columns.get_indexer(['species'])
target_col_idx


# Setting the X and y
X = new_df.iloc[:,feature_col_idx].to_numpy()
y = new_df.iloc[:,target_col_idx].to_numpy()
m,n = X.shape
y = y.reshape(m,1)

print("X.shape", X.shape)
print("y.shape", y.shape)

#### Transform standardized data back to original scale
We can transform standardized predicted values, y_predicted into the orginal data scale using$$y_{\text{norm}} = \sigma_y y + \mu_y$$

#### Adding random error to a function 

In [ ]:
def nl_func(x):
    return 2*x**2 + 4 + np.random.normal(loc=0, scale=15)
#Draw random samples from a normal (Gaussian) distribution.
#loc = mean
# scale = std


np.random.seed(42)
X = np.random.rand(1000,1)
y = 5*((X)**(2)) + np.random.rand(1000,1) # Random values in a given shape.


# Generate X
m = 100
X = np.random.uniform(-4, 4, (m,1))
# Generate y
q = 0.7
b = 1
c = 2
y = a * X**2 + b * X + c + np.random.randn(m, 1) #Return mx1 array 
#Return a sample (or samples) from the “standard normal” distribution.
#Draw samples from a standard Normal distribution (mean=0, stdev=1).

#### np.where

In [ ]:
idx_0 = np.where(y == 0)
idx_1 = np.where(y == 1)

#### Boolean to int array

In [ ]:
y_test_pred_hard = (y_test_pred_soft > 0.5).astype(int)

#### Identity Matrix

In [ ]:
Q = np.eye(3);

#### Inserting

In [23]:
X1 = np.array([
    [5, 4],
    [6, 3]
]) 

In [24]:
X1_2 = X1[:,0]**2
X1_2.shape

(2,)

In [25]:
m,n = X1.shape
X1_2.reshape(1,m)
X1_2.shape

(2,)

In [26]:
X1_2

array([25, 36])

In [27]:
X_new = np.insert(X1, 2, X1_2, axis=1)

In [28]:
X_new

array([[ 5,  4, 25],
       [ 6,  3, 36]])

In [3]:
import numpy as np

array_1 = np.array([2,4,6,8,10,12])
print("Array 1: \n", array_1)

array_2 = np.array([4,8,12,13])
print("\nArray 2: \n", array_2)

set_diff = np.setdiff1d(array_2, array_1)
print("\nThe set difference between array_1 and array_2 is:\n",set_diff)

Array 1: 
 [ 2  4  6  8 10 12]

Array 2: 
 [ 4  8 12 13]

The set difference between array_1 and array_2 is:
 [13]


### Pandas

In [ ]:
import pandas as pd
import numpy as np
import random

# Import the data

df = pd.read_csv('final-exam-data.csv')
df.head()


df.columns

from sklearn.model_selection import train_test_split

X = df[['# x1', 'x2']]
y = df['y']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=999)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

In [5]:
a = np.arange(6)
b = a.reshape((3, 2))
b.shape, a.shape


((3, 2), (6,))